"""add company_checks table

Revision ID: b846bbbab0b3
Revises: d4e5f6a7b8c9
Create Date: 2026-06-09 13:12:47.237967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b846bbbab0b3'
down_revision = 'd4e5f6a7b8c9'
branch_labels = None
depends_on = None


def upgrade():
    # Drop legacy Buratino-era tables — use IF EXISTS because some deployments
    # already had these removed via inline migrations before Alembic was added.
    op.execute("DROP INDEX IF EXISTS ix_social_profiles_platform_id")
    op.execute("DROP INDEX IF EXISTS ix_social_profiles_username")
    op.execute("DROP TABLE IF EXISTS social_profiles")
    op.execute("DROP TABLE IF EXISTS connections")
    op.execute("DROP INDEX IF EXISTS ix_business_records_inn")
    op.execute("DROP INDEX IF EXISTS ix_business_records_ogrn")
    op.execute("DROP TABLE IF EXISTS business_records")
    op.execute("DROP INDEX IF EXISTS ix_friends_platform_id")
    op.execute("DROP TABLE IF EXISTS friends")
    op.execute("DROP INDEX IF EXISTS ix_court_records_case_number")
    op.execute("DROP TABLE IF EXISTS court_records")
    op.execute("DROP TABLE IF EXISTS investigations")
    op.execute("DROP INDEX IF EXISTS idx_chat_messages_user_id")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_chat_messages_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('candidate_checks', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'investigations', ['investigation_id'], ['id'])

    op.create_table('investigations',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('input_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('input_name_cyrillic', sa.VARCHAR(length=255), nullable=True),
    sa.Column('input_photo_path', sa.VARCHAR(length=500), nullable=True),
    sa.Column('_discovered_usernames', sa.TEXT(), nullable=True),
    sa.Column('_discovered_profiles', sa.TEXT(), nullable=True),
    sa.Column('_phase1_stats', sa.TEXT(), nullable=True),
    sa.Column('_confirmed_profile', sa.TEXT(), nullable=True),
    sa.Column('profile_confirmed_at', sa.DATETIME(), nullable=True),
    sa.Column('confirmed_username', sa.VARCHAR(length=255), nullable=True),
    sa.Column('confirmed_platform', sa.VARCHAR(length=50), nullable=True),
    sa.Column('confirmed_profile_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('confirmed_photo_verified', sa.BOOLEAN(), nullable=True),
    sa.Column('_discovered_emails', sa.TEXT(), nullable=True),
    sa.Column('_discovered_phones', sa.TEXT(), nullable=True),
    sa.Column('confirmed_email', sa.VARCHAR(length=255), nullable=True),
    sa.Column('confirmed_phone', sa.VARCHAR(length=50), nullable=True),
    sa.Column('_cross_validation_results', sa.TEXT(), nullable=True),
    sa.Column('_business_records', sa.TEXT(), nullable=True),
    sa.Column('_court_records', sa.TEXT(), nullable=True),
    sa.Column('_property_records', sa.TEXT(), nullable=True),
    sa.Column('_alternate_accounts', sa.TEXT(), nullable=True),
    sa.Column('_group_memberships', sa.TEXT(), nullable=True),
    sa.Column('_additional_findings', sa.TEXT(), nullable=True),
    sa.Column('_social_graph', sa.TEXT(), nullable=True),
    sa.Column('_connections', sa.TEXT(), nullable=True),
    sa.Column('_risk_indicators', sa.TEXT(), nullable=True),
    sa.Column('identity_card_generated', sa.BOOLEAN(), nullable=True),
    sa.Column('identity_card_path', sa.VARCHAR(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('court_records',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('investigation_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('case_number', sa.VARCHAR(length=100), nullable=True),
    sa.Column('unique_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('category', sa.VARCHAR(length=50), nullable=True),
    sa.Column('subcategory', sa.VARCHAR(length=100), nullable=True),
    sa.Column('status', sa.VARCHAR(length=100), nullable=True),
    sa.Column('court_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('court_level', sa.VARCHAR(length=50), nullable=True),
    sa.Column('court_region', sa.VARCHAR(length=100), nullable=True),
    sa.Column('judge_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('filing_date', sa.DATE(), nullable=True),
    sa.Column('hearing_date', sa.DATE(), nullable=True),
    sa.Column('decision_date', sa.DATE(), nullable=True),
    sa.Column('effective_date', sa.DATE(), nullable=True),
    sa.Column('person_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('person_role', sa.VARCHAR(length=100), nullable=True),
    sa.Column('person_inn', sa.VARCHAR(length=12), nullable=True),
    sa.Column('_participants', sa.TEXT(), nullable=True),
    sa.Column('subject', sa.TEXT(), nullable=True),
    sa.Column('claim_amount', sa.FLOAT(), nullable=True),
    sa.Column('awarded_amount', sa.FLOAT(), nullable=True),
    sa.Column('decision_type', sa.VARCHAR(length=100), nullable=True),
    sa.Column('decision_summary', sa.TEXT(), nullable=True),
    sa.Column('_documents', sa.TEXT(), nullable=True),
    sa.Column('source', sa.VARCHAR(length=100), nullable=True),
    sa.Column('source_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('is_defendant', sa.BOOLEAN(), nullable=True),
    sa.Column('is_negative', sa.BOOLEAN(), nullable=True),
    sa.Column('risk_score', sa.FLOAT(), nullable=True),
    sa.Column('_raw_data', sa.TEXT(), nullable=True),
    sa.Column('discovered_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('court_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_court_records_case_number'), ['case_number'], unique=False)

    op.create_table('friends',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('investigation_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('parent_profile_id', sa.INTEGER(), nullable=True),
    sa.Column('platform', sa.VARCHAR(length=50), nullable=False),
    sa.Column('platform_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('username', sa.VARCHAR(length=255), nullable=True),
    sa.Column('profile_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('photo_url', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('city', sa.VARCHAR(length=255), nullable=True),
    sa.Column('country', sa.VARCHAR(length=255), nullable=True),
    sa.Column('age', sa.INTEGER(), nullable=True),
    sa.Column('gender', sa.VARCHAR(length=20), nullable=True),
    sa.Column('is_closed', sa.BOOLEAN(), nullable=True),
    sa.Column('relationship_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('mutual_friends_count', sa.INTEGER(), nullable=True),
    sa.Column('interaction_score', sa.FLOAT(), nullable=True),
    sa.Column('centrality_score', sa.FLOAT(), nullable=True),
    sa.Column('community_id', sa.INTEGER(), nullable=True),
    sa.Column('is_analyzed', sa.BOOLEAN(), nullable=True),
    sa.Column('is_flagged', sa.BOOLEAN(), nullable=True),
    sa.Column('discovered_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.ForeignKeyConstraint(['parent_profile_id'], ['social_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('friends', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_friends_platform_id'), ['platform_id'], unique=False)

    op.create_table('business_records',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('investigation_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('inn', sa.VARCHAR(length=12), nullable=True),
    sa.Column('ogrn', sa.VARCHAR(length=15), nullable=True),
    sa.Column('kpp', sa.VARCHAR(length=9), nullable=True),
    sa.Column('company_name', sa.VARCHAR(length=500), nullable=True),
    sa.Column('short_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('company_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('registration_date', sa.DATE(), nullable=True),
    sa.Column('liquidation_date', sa.DATE(), nullable=True),
    sa.Column('legal_address', sa.VARCHAR(length=500), nullable=True),
    sa.Column('region', sa.VARCHAR(length=100), nullable=True),
    sa.Column('city', sa.VARCHAR(length=100), nullable=True),
    sa.Column('person_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('role', sa.VARCHAR(length=100), nullable=True),
    sa.Column('role_start_date', sa.DATE(), nullable=True),
    sa.Column('role_end_date', sa.DATE(), nullable=True),
    sa.Column('share_percent', sa.FLOAT(), nullable=True),
    sa.Column('share_amount', sa.FLOAT(), nullable=True),
    sa.Column('authorized_capital', sa.FLOAT(), nullable=True),
    sa.Column('revenue', sa.FLOAT(), nullable=True),
    sa.Column('employees_count', sa.INTEGER(), nullable=True),
    sa.Column('main_okved', sa.VARCHAR(length=20), nullable=True),
    sa.Column('main_okved_name', sa.VARCHAR(length=500), nullable=True),
    sa.Column('_okved_codes', sa.TEXT(), nullable=True),
    sa.Column('tax_authority', sa.VARCHAR(length=255), nullable=True),
    sa.Column('tax_authority_code', sa.VARCHAR(length=10), nullable=True),
    sa.Column('source', sa.VARCHAR(length=100), nullable=True),
    sa.Column('source_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('_raw_data', sa.TEXT(), nullable=True),
    sa.Column('discovered_at', sa.DATETIME(), nullable=True),
    sa.Column('data_updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('business_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_business_records_ogrn'), ['ogrn'], unique=False)
        batch_op.create_index(batch_op.f('ix_business_records_inn'), ['inn'], unique=False)

    op.create_table('connections',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('investigation_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('source_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('source_id', sa.VARCHAR(length=500), nullable=True),
    sa.Column('source_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('source_photo_url', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('target_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('target_id', sa.VARCHAR(length=500), nullable=True),
    sa.Column('target_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('target_photo_url', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('connection_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('strength', sa.FLOAT(), nullable=True),
    sa.Column('_evidence', sa.TEXT(), nullable=True),
    sa.Column('platform', sa.VARCHAR(length=50), nullable=True),
    sa.Column('discovered_at', sa.DATETIME(), nullable=True),
    sa.Column('verified', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('social_profiles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('investigation_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('platform', sa.VARCHAR(length=50), nullable=False),
    sa.Column('platform_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('username', sa.VARCHAR(length=255), nullable=True),
    sa.Column('profile_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('display_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('photo_url', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('bio', sa.TEXT(), nullable=True),
    sa.Column('city', sa.VARCHAR(length=255), nullable=True),
    sa.Column('country', sa.VARCHAR(length=255), nullable=True),
    sa.Column('birth_date', sa.VARCHAR(length=50), nullable=True),
    sa.Column('age', sa.INTEGER(), nullable=True),
    sa.Column('gender', sa.VARCHAR(length=20), nullable=True),
    sa.Column('_education', sa.TEXT(), nullable=True),
    sa.Column('_career', sa.TEXT(), nullable=True),
    sa.Column('friends_count', sa.INTEGER(), nullable=True),
    sa.Column('followers_count', sa.INTEGER(), nullable=True),
    sa.Column('photos_count', sa.INTEGER(), nullable=True),
    sa.Column('groups_count', sa.INTEGER(), nullable=True),
    sa.Column('is_closed', sa.BOOLEAN(), nullable=True),
    sa.Column('can_access', sa.BOOLEAN(), nullable=True),
    sa.Column('is_confirmed', sa.BOOLEAN(), nullable=True),
    sa.Column('is_rejected', sa.BOOLEAN(), nullable=True),
    sa.Column('confirmed_at', sa.DATETIME(), nullable=True),
    sa.Column('confidence_score', sa.FLOAT(), nullable=True),
    sa.Column('confidence_level', sa.VARCHAR(length=20), nullable=True),
    sa.Column('face_match', sa.BOOLEAN(), nullable=True),
    sa.Column('face_similarity', sa.FLOAT(), nullable=True),
    sa.Column('name_match', sa.BOOLEAN(), nullable=True),
    sa.Column('name_similarity', sa.FLOAT(), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=50), nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), nullable=True),
    sa.Column('website', sa.VARCHAR(length=500), nullable=True),
    sa.Column('_social_links', sa.TEXT(), nullable=True),
    sa.Column('_raw_data', sa.TEXT(), nullable=True),
    sa.Column('discovered_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('investigation_id', 'platform', 'platform_id', name=op.f('uq_profile_platform'))
    )
    with op.batch_alter_table('social_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_social_profiles_username'), ['username'], unique=False)
        batch_op.create_index(batch_op.f('ix_social_profiles_platform_id'), ['platform_id'], unique=False)

    # ### end Alembic commands ###
